spring:
  application:
    name: bs-api
management:
  context_path: /admin
security:
  oauth2:
    client:
      authenticationScheme: header
  resource:
    filter-order: 3
logging:
  level:
    # org.springframework.security: DEBUG

---

spring:
  profiles: client
server:
  port: 2533
  